version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: agency_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agency_travel_db
      MYSQL_USER: agency_user
      MYSQL_PASSWORD: agency_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: